### ISSUE TITLE
AttributeError: realivised

### ISSUE THREAD

**Issue by Catadanna** [mapado/pynlg#10]
I get this error : 

```
File "/my/path/pynlg/spec/phrase.py", line 147, in realise
    return self.helper.realise(phrase=self)
  File "/my/path/pynlg/helper/fr.py", line 34, in realise
    if not phrase.realivised:
  File "/my/path/pynlg/spec/base.py", line 154, in __getattr__
    raise AttributeError(name)
AttributeError: realivised
```

Can someone help and tell me what is wrong ? I cannot debug.

I use : Ubuntu (Linux)

**Comment by jdeniau** [comment]
This come from [this line](https://github.com/mapado/pynlg/blob/8f9c7fb2264f1a7b3d1b3a3713028bdbefbe3244/pynlg/helper/fr.py#L35)

I tried to bypass this with `if not ('realivised' in phrase and phrase.realivised):`, but there is another error after that.

I'm sorry but I won't have more time to help you on that.

**Comment by Catadanna** [comment]
I saw it comes from that line, and that there are bugs afterwards. I see the code is no longer maintained, it is a pity, it is a good start. I shall manage with that, and inform you if I shall make it work.
