### ISSUE TITLE
Import error while running on Python 3.5 and Windows 10

### ISSUE THREAD

**Issue by danielvasic** [mapado/pynlg#5]
When I install pynlg on Windows running Python 3.6 it outputs this error: "ImportError: No module named 'lib\\site-packages\\pynlg-0'".
Any suggestions?

**Comment by AlJohri** [comment]
can you show the full traceback? how are you installing and running pynlg? seems to work for me on macOS:

![screen shot 2017-10-07 at 2 44 09 pm](https://user-images.githubusercontent.com/2790092/31310873-1665b850-ab6e-11e7-8269-797acc9f2870.png)

**Comment by danielvasic** [comment]
Hello @AlJohri 
Thanks for the response, it seems to be an issue with importlib?

![pynlg issue](https://user-images.githubusercontent.com/2452299/31311389-8dbddf30-abab-11e7-9fda-a8ab08e98b1e.png)

**Comment by AlJohri** [comment]
what command did you run to install pynlg?

**Comment by danielvasic** [comment]
I installed pynlg using pip - python -m pip install pynlg

**Comment by danielvasic** [comment]
I have installed it manually by running setup.py,  Now I get same error but different path.

![ss05](https://user-images.githubusercontent.com/2452299/31317737-90e9e898-ac46-11e7-8a64-405a2a07b933.jpg)

**Comment by tokiop** [comment]
Hello ! Does [this change](https://github.com/mapado/pynlg/compare/master...tokiop:patch-1) works for you ?
